routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('class_user/{user}', 'ClassController@class_user');
    //登录视图
    Route::get('login', 'LoginController@login');
    Route::get('jiami', 'LoginController@jiami');
    //登录处理
    Route::post('dologin', 'LoginController@dologin');
    //退出登录
    Route::get('logout', 'LoginController@logout');
    //修改密码
    Route::get('password', 'LoginController@password');
    //修改密码
    Route::post('dopass', 'LoginController@dopass');
    Route::group(['middleware' => 'islogin'], function () {
        //后台首页
        Route::get('index', 'LoginController@index');
        //授权界面
        Route::get('manage/{id}/auth', 'ManageController@auth');
        //授权处理
        Route::post('manage/doauth', 'ManageController@doauth');
        //管理员主页数据
        Route::get('manage/data', 'ManageController@data');
        //管理员管理
        Route::resource('manage', 'ManageController');

        //学期模块相关路由
        Route::group(['prefix' => 'term'], function () {
            Route::get('index', 'TermController@Index');
            Route::get('data', 'TermController@data');
            Route::get('create', 'TermController@Create');
            Route::get('{id}/update', 'TermController@Update');
            Route::post('add', 'TermController@Add');
            Route::put('edit/{id}', 'TermController@Edit');
            Route::get('del/{id}', 'TermController@Del');
            Route::post('tag/{id}', 'TermController@tag');
        });
        //周次模块相关路由
        Route::group(['prefix' => 'week'], function () {
            Route::get('index', 'WeekController@Index');
            Route::get('data', 'WeekController@data');
            Route::get('create', 'WeekController@Create');
            Route::get('{id}/update', 'WeekController@Update');
            Route::post('add', 'WeekController@Add');
            Route::put('edit/{id}', 'WeekController@Edit');
            Route::get('del/{id}', 'WeekController@Del');
            Route::post('tag/{id}', 'WeekController@tag');
        });
        //班级模块相关路由
        Route::group(['prefix' => 'class'], function () {
            Route::get('index', 'ClassController@Index');
            Route::get('data', 'ClassController@data');
            Route::get('create', 'ClassController@Create');
            Route::get('{id}/update', 'ClassController@Update');
            Route::post('add', 'ClassController@Add');
            Route::put('edit/{id}', 'ClassController@Edit');
            Route::get('del/{id}', 'ClassController@Del');
            Route::post('tag/{id}', 'ClassController@tag');
        });
        //班级模块相关路由
        Route::group(['prefix' => 'class_stu'], function () {
            //授权界面
            Route::get('{id}/auth', 'StuController@auth');
            //授权处理
            Route::post('doauth', 'StuController@doauth');
            Route::get('index', 'StuController@Index');
            Route::get('data', 'StuController@data');
            Route::get('create', 'StuController@Create');
            Route::get('{id}/update', 'StuController@Update');
            Route::post('add', 'StuController@Add');
            Route::put('edit/{id}', 'StuController@Edit');
            Route::get('del/{id}', 'StuController@delete');
        });
        //班级大事纪模块相关路由
        Route::group(['prefix' => 'event'], function () {
            Route::get('index', 'EventController@Index');
            Route::get('data', 'EventController@data');
            Route::get('create', 'EventController@Create');
            Route::get('{id}/update', 'EventController@Update');
            Route::post('add', 'EventController@Add');
            Route::put('edit/{id}', 'EventController@Edit');
            Route::get('del/{id}', 'EventController@Del');
            Route::post('tag/{id}', 'EventController@tag');

        });
        Route::group(['prefix' => 'materials'], function () {
            Route::get('data/{id}','MaterialsController@data');
            Route::get('{id}/create', 'MaterialsController@index');
            Route::post('add/{id}', 'MaterialsController@add');
            Route::get('{id}/update', 'MaterialsController@update');
            Route::put('edit/{id}', 'MaterialsController@edit');
            Route::post('upload', 'MaterialsController@upload');
            Route::get('del/{id}', 'MaterialsController@Del');
        });

        //班级大事纪文件模块相关路由
        Route::group(['prefix' => 'eventfile'], function () {
            Route::get('index', 'EventFileController@Index');
            Route::get('data', 'EventFileController@data');
            Route::get('create', 'EventFileController@Create');
            Route::get('{id}/update', 'EventFileController@Update');
            Route::post('add', 'EventFileController@Add');
            Route::put('edit/{id}', 'EventFileController@Edit');
            Route::get('del/{id}', 'EventFileController@Del');
            Route::post('tag/{id}', 'EventFileController@tag');
            Route::post('upload', 'EventFileController@upload');
        });
        //加减分模块相关路由
        Route::group(['prefix' => 'points'], function () {
            Route::get('index', 'PointsController@Index');
            Route::get('index2', 'PointsController@Index2');
            Route::get('data', 'PointsController@data');
            Route::get('data2', 'PointsController@data2');
            Route::get('create', 'PointsController@Create');
            Route::get('{id}/update', 'PointsController@Update');
            Route::get('create2', 'PointsController@Create2');
            Route::get('{id}/update2', 'PointsController@Update2');
            Route::post('add', 'PointsController@Add');
            Route::put('edit/{id}', 'PointsController@Edit');
            Route::get('del/{id}', 'PointsController@Del');
            Route::post('tag/{id}', 'PointsController@tag');
            Route::post('classnmae', 'PointsController@classname');
        });
        //任务模块相关路由
        Route::group(['prefix' => 'task'], function () {
            Route::get('index', 'TaskController@Index');
            Route::get('index2', 'TaskController@Index2');
            Route::get('index6', 'TaskController@Index6');
            Route::get('data', 'TaskController@data');
            Route::get('{id}/check', 'TaskController@check');
            Route::post('docheck', 'TaskController@docheck');
            Route::get('data2/{id}', 'TaskController@data2');
            Route::get('data3', 'TaskController@data3');
            Route::get('data4', 'TaskController@data4');
            Route::get('data5/{id}', 'TaskController@data5');
            Route::get('data6', 'TaskController@data6');
            Route::get('{id}/details', 'TaskController@details');
            Route::get('create', 'TaskController@Create');
            Route::get('create2', 'TaskController@Create2');
            Route::get('{id}/update', 'TaskController@Update');
            Route::post('add', 'TaskController@Add');
            Route::put('edit/{id}', 'TaskController@Edit');
            Route::get('del/{id}', 'TaskController@Del');
            Route::post('tag/{id}', 'TaskController@tag');
            Route::post('tree', 'TaskController@tree');
            Route::post('upload', 'TaskController@upload');
            Route::get('show', 'TaskController@show');
            Route::get('{id}/end', 'TaskController@end');
            Route::post('doend', 'TaskController@doend');
            Route::get('{id}/toview', 'TaskController@toview');
            Route::get('{id}/toview2', 'TaskController@toview2');
            Route::get('{id}/toview3', 'TaskController@toview3');
            Route::get('doview/{id}', 'TaskController@doview');
        });
        //角色主页数据
        Route::get('role/data', 'RoleController@data');
        //角色授权
        Route::get('role/{id}/auth', 'RoleController@auth');
        //处理授权
        Route::post('role/doauth', 'RoleController@doauth');
        //删除
        Route::get('role/destroy/{id}', 'RoleController@destroy');
        //角色管理
        Route::resource('role', 'RoleController');


        //节点主页数据
        Route::get('node/data', 'NodeController@data');
        Route::get('node/data2', 'NodeController@data2');
        //修改
        Route::get('node/{id}/edit2', 'NodeController@edit2');
        //删除
        Route::get('role/destroy/{id}', 'RoleController@destroy');
        Route::get('node/destroy/{id}', 'NodeController@destroy');
        //节点管理
        Route::resource('node', 'NodeController');
    });

});

app/Models/Points.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Points extends Model
{
    //1.关联的数据表
    public $table = 'points';
    //2.主键
    public $primaryKey = 'id';
    //3.允许批量操作的字段
    public $guarded = [];
    //4.是否维护crated_at和updated_at字段
    public $timestamps = false;

    public function class()
    {
        return $this->belongsTo(Classname::class, 'class_id');
    }

    public function getClassNameAttribute($key)
    {
        return $this->class['name'];

    }

    public function stu()
    {
        return $this->belongsTo(Stu::class, 'stu_id');
    }

    public function getStuNameAttribute($key)
    {
        return $this->stu['user_name'];

    }

    public function week()
    {
        return $this->belongsTo(Week::class, 'week_id');
    }

    public function getWeekNameAttribute($key)
    {
        return '第' . $this->week['xh'] . '周';

    }

    protected $appends = ['classname', 'weekname', 'stuname'];
}

resources/views/admin/class_stu/auth.blade.php
@extends('layouts.admin')

@section('nav')
    @include('admin/class_stu/nav')
@endsection

@section('cont')
    <form action="{{ url('admin/class_stu/doauth') }}" class="form-horizontal" role="form" method="post">
        {{ csrf_field() }}

        <input type="hidden" name="stu_id" value="{{ $stu->id }}">

        <table id="simple-table" class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <td style="text-align:left;" colspan="2">
                    用户名： {{ $stu->stu_name }}
                </td>
            </tr>
            </thead>
            <tr>
                <td style="text-align:left;" colspan="2">
                    <div class="form-group">
                        <label for="show_tag" class="col-xs-12 col-sm-3 control-label no-padding-right">授权：</label>

                        <div class="col-xs-12 col-sm-5">
            <span class="block input-icon input-icon-right">
                <div class="radio inline">
                    @foreach($roleall as $v)
                        <label>
                           <input name="role_id" type="radio" value="{{$v->id}}" @if($v->id==$stu->role_id) checked
                                  @endif class="ace"/>
                           <span class="lbl"> {{$v->name}}</span>
                       </label>
                    @endforeach
                </div>
            </span>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2" width="100%" class="center">
                    <input type="submit" class="btn btn-info"></input>
                </td>
            </tr>
        </table>
    </form>

@endsection

resources/views/admin/class_stu/create.blade.php
@extends('layouts.admin')

@section('nav')
    @include('admin/class_stu/nav')
@endsection

@section('cont')
    <form class="form-horizontal" id="sample-form" method="post" action="{{url('admin/class_stu/add')}}">
        {{ csrf_field() }}
        <div class="form-group">
            <label for="name" class="col-xs-12 col-sm-3 control-label no-padding-right">班级选择：</label>

            <div class="col-xs-12 col-sm-5">
            <span class="block input-icon input-icon-right">
                @if($cont>1)
                    <select name="pid" id="ctype_id" class="singleSelect width-100">
                    <option value="0">请选择班级</option>
                    @foreach($class as $v)
                            <option value="{{$v->id}}">{{$v->name}}</option>
                        @endforeach
                </select>
                @else
                    <select name="pid" id="ctype_id" class=" width-100">
                    @foreach($class as $v)
                            <option value="{{$v->id}}">{{$v->name}}</option>
                        @endforeach
                </select>
                @endif
            </span>
            </div>
            <div class="help-block col-xs-12 col-sm-reset inline red">
                *(必填)
            </div>
        </div>
        <div class="form-group">
            <label for="name" class="col-xs-12 col-sm-3 control-label no-padding-right">学生姓名：</label>

            <div class="col-xs-12 col-sm-5">
                <span class="block input-icon input-icon-right">
                    <input type="text" name="stu_name" required="" id="name" class="width-100"
                           autocomplete="off">
                    <i class="icon-leaf"></i>
                </span>
            </div>
            <div id="xiaoxi" class="help-block col-xs-12 col-sm-reset inline red">
                *(必填)
            </div>
        </div>
        <div class="form-group">
            <label for="name" class="col-xs-12 col-sm-3 control-label no-padding-right">学生学号：</label>

            <div class="col-xs-12 col-sm-5">
                <span class="block input-icon input-icon-right">
                    <input type="text" name="stu_xh" required="" id="name" class="width-100"
                           autocomplete="off">
                    <i class="icon-leaf"></i>
                </span>
            </div>
            <div id="xiaoxi" class="help-block col-xs-12 col-sm-reset inline red">
                *(必填)
            </div>
        </div>
        <div class="form-group">
            <label for="password" class="col-xs-12 col-sm-3 control-label no-padding-right">密码：</label>

            <div class="col-xs-12 col-sm-5">
                <span class="block input-icon input-icon-right">
                    <input type="password" name="password" required="" id="password" class="width-100"
                           autocomplete="off">
                    <i class="icon-leaf"></i>
                </span>
            </div>
            <div id="password_id" class="help-block col-xs-12 col-sm-reset inline red">
                *(必填)
            </div>
        </div>
        <div class="form-group">
            <label for="password" class="col-xs-12 col-sm-3 control-label no-padding-right">重复密码：</label>

            <div class="col-xs-12 col-sm-5">
                <span class="block input-icon input-icon-right">
                    <input type="password" name="password2" required="" id="password2" class="width-100"
                           autocomplete="off">
                    <i class="icon-leaf"></i>
                </span>
            </div>
            <div id="password_id2" class="help-block col-xs-12 col-sm-reset inline red">
                *(必填)
            </div>
        </div>
        <div class="form-group">
            <label for="remark" class="col-xs-12 col-sm-3 control-label no-padding-right">备注信息：</label>

            <div class="col-xs-12 col-sm-5">
                <span class="block input-icon input-icon-right">
                    <input type="text" name="bz" id="remark" class="width-100">
                    <i class="icon-leaf"></i>
                </span>
            </div>
            <div class="help-block col-xs-12 col-sm-reset inline">

            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-12 col-sm-5 col-sm-offset-4">
                <button class="btn btn-success" onclick="">提交</button>&nbsp;&nbsp;&nbsp;
                <button class="btn btn-warning" type="reset">重置</button>
            </div>
        </div>
    </form>
@endsection

@section('js')
    <script>
        //一、对姓名进行验证
        var oldxiaoxi;
        var oldclass;
        //姓名获取焦点时显示，内含失去焦点显示点击前样式及内容
        $("#name").focus(function () {
            oldxiaoxi = $("#xiaoxi").text();
            oldclass = $("#xiaoxi").attr("class");
            //修改css样式为黑色
            $("#xiaoxi").attr("class", "help-block col-xs-12 col-sm-reset inline");
            //修改HTML内容
            $("#xiaoxi").html("(正在输入...)");
            //当点击完输入框不做操作离开时避免显示正在输入，因此显示点击前所显示的内容及样式
            // $("#name").blur(function() {
            //     //修改css内容
            //     $("#xiaoxi").attr("class",oldclass);
            //     //修改HTML内容
            //     $("#xiaoxi").html(oldxiaoxi);
            // });
        });

        var oldxiaoxi1;
        var oldclass1;
        //键盘离开时显示，内含失去焦点显示键盘离开后样式及内容
        $("#name").keyup(function () {
            var name = $(" #name ").val();
            if (name === '') {
                //修改css样式为黑色
                $("#xiaoxi").attr("class", "help-block col-xs-12 col-sm-reset inline");
                //修改HTML内容
                $("#xiaoxi").html("(正在输入...)");
            } else {
                //调用ajax
                $.ajax({
                    //请求方式
                    type: "post",

                    //服务器相应数据的解析方式
                    dataType: "json",
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    //请求资源url
                    url: "/admin/manager",
                    //此处需要同步处理，即ajax执行完后才能向下进行。（避免第一次点击输入框只有一次键盘触发时oldxiaoxi为（正在输入...））
                    // async: false,
                    //向服务器端发送的数据
                    data: {"name": name, "ajax": 'cunzai'},
                    success: function (data) {
                        $("#xiaoxi").attr("class", data.newclass);
                        $("#xiaoxi").html(data.cont);
                        oldxiaoxi1 = $("#xiaoxi").text();
                        oldclass1 = $("#xiaoxi").attr("class");
                    }
                });
            }

        });

        //失去焦点时的两种情况，1.获取焦点->失去焦点，2.获取焦点->键盘离开->失去焦点（最后一个else之后便是）
        $("#name").blur(function () {
            if ($(" #name ").val() === '') {
                //修改css样式为黑色
                $("#xiaoxi").attr("class", "help-block col-xs-12 col-sm-reset inline red");
                //修改HTML内容
                $("#xiaoxi").html("*必填");
            } else {
                if (oldxiaoxi1 === "(用户名已存在)") {
                    $("#name").val("");
                    //修改css内容
                    $("#xiaoxi").attr("class", "help-block col-xs-12 col-sm-reset inline red");
                    //修改HTML内容
                    $("#xiaoxi").html("*(必填)");
                } else if (oldxiaoxi1 === "(用户名可用)") {
                    // 修改css内容
                    $("#xiaoxi").attr("class", oldclass1);
                    //修改HTML内容
                    $("#xiaoxi").html(oldxiaoxi1);
                } else {
                    //修改css内容
                    $("#xiaoxi").attr("class", oldclass);
                    //修改HTML内容
                    $("#xiaoxi").html(oldxiaoxi);
                }
            }
        });


        //二、对密码进行验证
        var oldpassword_x;
        var oldpassword_c;
        //姓名获取焦点时显示，内含失去焦点显示点击前样式及内容
        $("#password").focus(function () {
            oldpassword_x = $("#password_id").text();
            oldpassword_c = $("#password_id").attr("class");
            //修改css样式为黑色
            $("#password_id").attr("class", "help-block col-xs-12 col-sm-reset inline");
            //修改HTML内容
            $("#password_id").html("(请输入6-16位数字、字母或常用符号，字母区分大小写)");
        });


        var qiangdu;
        //键盘离开时.
        $('#password').keyup(function () {
            //密码为八位及以上并且字母数字特殊字符三项都包括
            var strongRegex = new RegExp("^(?=.{6,})((?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*\\W))|((?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])).*$", "g");
            //密码为七位及以上并且字母、数字、特殊字符三项中有两项，强度是中等
            var mediumRegex = new RegExp("^(?=.{6,})(((?=.*[A-Z])(?=.*[a-z]))|((?=.*[A-Z])(?=.*[0-9]))|((?=.*[a-z])(?=.*[0-9]))).*$", "g");
            //密码为六位及及以上，只含有一种，强度为弱
            var enoughRegex = new RegExp("(?=.{6,}).*", "g");
            if (false == enoughRegex.test($('#password').val())) {
                $("#password_id").attr("class", "help-block col-xs-12 col-sm-reset inline");
                $("#password_id").html("(请输入6-16位数字、字母或常用符号，字母区分大小写)");
                qiangdu = 0;
            } else if (strongRegex.test($('#password').val())) {
                $("#password_id").attr("class", "help-block col-xs-12 col-sm-reset inline green");
                $("#password_id").html("(强：您的密码很安全！)");
                qiangdu = 1;
            } else if (mediumRegex.test($('#password').val())) {
                $("#password_id").attr("class", "help-block col-xs-12 col-sm-reset inline blue");
                $("#password_id").html("(中：您的密码号可以更复杂些！)");
                qiangdu = 2;
            } else {
                $("#password_id").attr("class", "help-block col-xs-12 col-sm-reset inline red");
                $("#password_id").html("(弱：您输入的密码强度过弱，试试字母、数字、常用符号的组合！)");
                qiangdu = 3;
            }
            return true;
        });

        $("#password").blur(function () {
            if (qiangdu == 0) {
                $("#password").val("");
                $("#password_id").attr("class", "help-block col-xs-12 col-sm-reset inline red");
                $("#password_id").html("*必填");
            } else if (qiangdu == 1) {
                $("#password_id").attr("class", "help-block col-xs-12 col-sm-reset inline green");
                $("#password_id").html("(强：您的密码很安全！)");
            } else if (qiangdu == 2) {
                $("#password_id").attr("class", "help-block col-xs-12 col-sm-reset inline blue");
                $("#password_id").html("(中：您的密码号可以更复杂些！)");
            } else if (qiangdu == 3) {
                $("#password_id").attr("class", "help-block col-xs-12 col-sm-reset inline red");
                $("#password_id").html("(弱：您输入的密码强度过弱，试试字母、数字、常用符号的组合！)");
            } else {
                $("#password_id").attr("class", oldpassword_c);
                $("#password_id").html(oldpassword_x);
            }
        });
        //一、对姓名进行验证
        var oldxiaoxi;
        var oldclass;
        //姓名获取焦点时显示，内含失去焦点显示点击前样式及内容
        $("#password2").focus(function () {
            oldxiaoxi = $("#password_id2").text();
            oldclass = $("#password_id2").attr("class");
            //修改css样式为黑色
            $("#password_id2").attr("class", "help-block col-xs-12 col-sm-reset inline");
            //修改HTML内容
            $("#password_id2").html("输入与上次密码一致");
            // 当点击完输入框不做操作离开时避免显示正在输入，因此显示点击前所显示的内容及样式
            $("#password2").blur(function () {
                //修改css内容
                $("#password_id2").attr("class", oldclass);
                //修改HTML内容
                $("#password_id2").html(oldxiaoxi);
            });
        });

    </script>
@endsection

resources/views/admin/class_stu/list.blade.php
@extends('layouts.admin')

@section('nav')
    @include('admin/class_stu/nav')
@endsection

@section('cont')
    <div id="toolbar" class="btn-group">
        <a href="{{url('admin/class_stu/create')}}" style="color:#333">
            <div id="btn_add" class="btn btn-default">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                新增
            </div>
        </a>
        <select id="class_id" style="width: 200px">
            @if($uid==0)
                <option value="">请选择班级</option>
            @endif
            @foreach($class as $v)
                <option value="{{$v->id}}">
                    {{$v->name}}
                </option>
            @endforeach
        </select>
    </div>
    <table id="tb_departments" class="table table-hover table-striped" style="margin-top: 0px;">

    </table>

    <div class="clearfix"></div>
    <script type="text/javascript">
        $(function () {
            //1.初始化Table
            var oTable = new TableInit();
            oTable.Init();

            //2.初始化Button的点击事件
            var oButtonInit = new ButtonInit();
            oButtonInit.Init();

            //3.初始化select的change事件
            $("#class_id").change(function () {
                $('#tb_departments').bootstrapTable('refreshOptions', {
                    exportDataType: $(this).val()
                });
            });
        });

        var TableInit = function () {
            var oTableInit = new Object();
            //初始化Table
            oTableInit.Init = function () {
                $('#tb_departments').bootstrapTable({
                    url: "{{ url('admin/class_stu/data') }}",         //请求后台的URL（*）
                    method: 'get',                      //请求方式（*）
                    toolbar: '#toolbar',                //工具按钮用哪个容器
                    striped: true,                      //是否显示行间隔色
                    cache: false,                       //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
                    pagination: true,                   //是否显示分页（*）
                    sortable: true,                     //是否启用排序
                    sortOrder: "asc",                   //排序方式
                    queryParams: oTableInit.queryParams,//传递参数（*）
                    sidePagination: "client",           //分页方式：client客户端分页，server服务端分页（*）
                    pageNumber: 1,                       //初始化加载第一页，默认第一页
                    pageSize: 10,                       //每页的记录行数（*）
                    pageList: [10, 25, 50, 100],        //可供选择的每页的行数（*）
                    search: true,                       //是否显示表格搜索

                    // strictSearch: true, //是否启用全匹配搜索
                    showColumns: true,                  //是否显示所有的列
                    showRefresh: true,              //是否显示刷新按钮
                    // showPaginationSwitch: true,
                    minimumCountColumns: 2,             //最少允许的列数
                    // clickToSelect: true,                //是否启用点击选中行
                    // height: 500,                        //行高，如果没有设置height属性，表格自动根据记录条数觉得表格高度
                    uniqueId: "id",                     //每一行的唯一标识，一般为主键列
                    showToggle: true,                    //是否显示详细视图和列表视图的切换按钮
                    cardView: false,                    //是否显示详细视图
                    // detailView: true,                   //是否显示父子表
                    showExport: true,
                    exportDataType: "basic",
                    // 注册加载子表的事件。注意下这里的三个参数！
                    onExpandRow: function (index, row, $detail) {
                        show(index, row, $detail);
                    },
                    // onDblClickCell:function(field,value,row,$element){
                    //     show(field,value,row,$element);
                    // },
                    columns: [
                        {
                            title: '序号',
                            formatter: function (value, row, index) {
                                return index + 1;
                            },
                            sortable: true
                        }, {
                            field: 'user_name',
                            title: '学生姓名',
                        }, {
                            field: 'classname',
                            title: '所属班级',
                        }, {
                            field: 'rolename',
                            title: '角色',
                        }, {
                            field: 'stu_xh',
                            title: '学生学号',
                        }, {
                            field: 'last_time',
                            title: '最近登录时间',
                        }, {
                            field: 'add_user',
                            title: '添加人',
                        }, {
                            field: 'add_time',
                            title: '添加时间',
                            sortable: true
                        }, {
                            field: 'id',
                            formatter: function (value, row, index) {
                                var a = "";
                                // a += "<a class='btn btn-xs btn-warning' href='/admin/class_stu/" + value + "/auth'>授权</a> ";
                                a += "<a class='btn btn-xs btn-info' href='/admin/class_stu/" + value + "/update'>编辑</a> ";
                                a += "<a class='btn btn-xs btn-danger' onclick='return del()' href='/admin/class_stu/del/" + value + "'>删除</a>";
                                return a;
                            },
                            title: '操作',
                        },
                    ]
                });
            };

            //得到查询的参数
            oTableInit.queryParams = function (params) {
                var temp = {   //这里的键的名字和控制器的变量名必须一直，这边改动，控制器也需要改成一样的
                    limit: params.limit,   //页面大小
                    offset: params.offset,  //页码
                    class_id: $("#class_id").val(),
                    statu: $("#txt_search_statu").val()
                };
                return temp;
            };
            return oTableInit;
        };


        var ButtonInit = function () {
            var oInit = new Object();
            var postdata = {};

            oInit.Init = function () {
                //初始化页面上面的按钮事件

            };

            return oInit;
        };

    </script>

@endsection

resources/views/admin/class_stu/nav.blade.php
<ul class="nav nav-tabs">
    <li class="active">
        <a href="/admin/class_stu/index">
            <i class="green ace-icon fa fa-home bigger-120"></i>
            学生列表
        </a>
    </li>

    <li class="hidden">
        <a href="/admin/class_stu/create">
            学生添加
        </a>
    </li>
    <li class="hidden">
        <a href="/admin/class_stu/{{ isset($stu) ? $stu->id : '' }}/update">
            学生编辑
        </a>
    </li>
    <li class="hidden">
        <a href="/admin/class_stu/{{ isset($stu) ? $stu->id : '' }}/auth">
            学生授权
        </a>
    </li>
</ul>